/*19-05-2022*/

CREATE TABLE EMP
(
	ENAME CHAR(1),
    SAL INT NOT NULL,
    DEPTNO INT
);
DROP TABLE EMP;

CREATE TABLE DELETED_EMP
(
	ENAME CHAR(1),
    SAL INT NOT NULL,
    DEPTNO INT
);
DROP TABLE DELETED_EMP;

INSERT INTO EMP VALUES
('A', 5000,1),
('B', 5000, 1),
('C', 5000, 1),
('D', 3000, 2),
('E', 3000, 2);

CREATE TABLE DEPTOT
(
	DEPTNO INT,
    SALTOT INT
);
DROP TABLE DEPTOT;
INSERT INTO DEPTOT VALUES
(1, 0),
(2, 0);
SELECT * FROM DEPTOT;

CREATE TABLE TEMPP
(
	ENAME CHAR(1),
    REMARK VARCHAR(20),
    TIMESTMP DATETIME
);
TRUNCATE TEMPP;
DROP TABLE TEMPP;

DELIMITER //
CREATE TRIGGER BIEMP
BEFORE INSERT ON EMP FOR EACH ROW
BEGIN
	SET NEW.ENAME=UPPER(NEW.ENAME);             /*DATA CLEANSING*/
	INSERT INTO TEMPP VALUES(NEW.ENAME,'INSERTED', SYSDATE());
END; //
DELIMITER ;
DROP TRIGGER BIEMP;
INSERT INTO EMP VALUES ('F', 3000, 2);
SELECT * FROM TEMPP ORDER BY TIMESTMP DESC;

DELIMITER //
CREATE TRIGGER AIEMP
BEFORE INSERT ON EMP FOR EACH ROW
BEGIN
	INSERT INTO TEMPP VALUES(NEW.ENAME,'INSERT SUCCESS', SYSDATE());
    UPDATE DEPTOT SET SALTOT=SALTOT+NEW.SAL WHERE DEPTOT.DEPTNO=NEW.DEPTNO;
END; //
DELIMITER ;
DROP TRIGGER AIEMP;
INSERT INTO EMP VALUES ('g', NULL, 2);
INSERT INTO EMP VALUES ('g', 3000, 2);
SELECT * FROM TEMPP ORDER BY TIMESTMP DESC;
SELECT * FROM DEPTOT;
SHOW TRIGGERS;


DELIMITER //
CREATE TRIGGER BDEMP
BEFORE DELETE
ON EMP FOR EACH ROW
BEGIN
	INSERT INTO TEMPP VALUES(OLD.ENAME, 'DELETING', SYSDATE());
    INSERT INTO DELETED_EMP VALUES (OLD.ENAME, OLD.SAL, OLD.DEPTNO);
END; //
DELIMITER ;
DROP TRIGGER BDEMP;
DELETE FROM EMP WHERE ENAME='G';
SELECT * FROM TEMPP ORDER BY TIMESTMP DESC;
SELECT * FROM DELETED_EMP;


DELIMITER //
CREATE TRIGGER ADEMP
AFTER DELETE
ON EMP FOR EACH ROW
BEGIN
	UPDATE DEPTOT SET SALTOT=SALTOT-OLD.SAL WHERE DEPTNO=OLD.DEPTNO;
	INSERT INTO TEMPP VALUES(OLD.ENAME, 'DELETED', SYSDATE());
END; //
DELIMITER ;
DROP TRIGGER ADEMP;
DELETE FROM EMP WHERE ENAME='F';
SELECT * FROM TEMPP ORDER BY TIMESTMP DESC;
SELECT * FROM DELETED_EMP;
SELECT * FROM EMP;
SELECT * FROM DEPTOT;
DELETE FROM EMP WHERE ENAME='G';


DELIMITER //
CREATE TRIGGER AUEMP
AFTER UPDATE
ON EMP FOR EACH ROW
BEGIN
	IF OLD.ENAME!=NEW.ENAME THEN
		INSERT INTO TEMPP VALUES (OLD.ENAME, 'NAME UPDATED', SYSDATE());
	END IF;
    IF OLD.DEPTNO <> NEW.DEPTNO THEN
		UPDATE DEPTOT SET SALTOT=SALTOT-OLD.SAL WHERE DEPTNO=OLD.DEPTNO;
        UPDATE DEPTOT SET SALTOT=SALTOT+NEW.SAL WHERE DEPTNO=NEW.DEPTNO;
        INSERT INTO TEMPP VALUES (OLD.ENAME, 'DEPT UPDATED', SYSDATE());
	ELSEIF ((OLD.DEPTNO =NEW.DEPTNO) AND (OLD.SAL!=NEW.SAL)) THEN 
		UPDATE DEPTOT SET SALTOT=SALTOT-OLD.SAL+NEW.SAL WHERE DEPTNO=NEW.DEPTNO;
		INSERT INTO TEMPP VALUES(OLD.ENAME, 'SAL UPDATED', SYSDATE());
	END IF;
END; //
DELIMITER ;
DROP TRIGGER AUEMP;
SELECT * FROM TEMPP ORDER BY TIMESTMP DESC;
SELECT * FROM DELETED_EMP;
SELECT * FROM EMP;
SELECT * FROM DEPTOT;
UPDATE EMP SET SAL=6000 WHERE SAL=5000;
UPDATE EMP SET DEPTNO=2, SAL=4000 WHERE ENAME='A'; 
UPDATE EMP SET ENAME='Z' WHERE ENAME='A';




